<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Asignar reporte
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "soporte/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="span3 offset4">
    <div class='form-group'>
        <?php
        echo "<img src=../../$ruta/$archivo>";
        ?>
    </div>

    <div class="form-group">
        <label>Prioridad</label>
        <div>
            <?php echo $this->tag->textField(["prioridad", "class" => "form-control disable", "id" => "fieldPrioridad", "readonly"=>"readonly"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label>Nombre</label>
        <div>
            <?php echo $this->tag->textField(["nombre", "class" => "form-control disable", "id" => "fieldNombre", "readonly"=>"readonly"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label>Descripcion</label>
        <div>
            <?php echo $this->tag->textArea(["descripcion", "class" => "form-control", "id" => "fieldDescripcion", "readonly"=>"readonly"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label>Usuario</label>
        <div align="center">
            <?php
            echo $this->tag->select(["id_usuario",$usuario,'using'=>['id_usuario','nombreC'],"class" => "form-control"]) ?>
        </div>
    </div>

    <div class="form-group">
        <label>Comentario</label>
        <div>
            <?php echo $this->tag->textArea(["comentario", "class" => "form-control", "id" => "fieldComentario"]) ?>
        </div>
    </div>

    <?php echo $this->tag->hiddenField("id_reporte") ?>

    <div class="form-group">
        <div align="center">
            <?php echo $this->tag->submitButton(["Asignar", "class" => "btn btn-success"]) ?>
        </div>
    </div>
</div>
<?php echo $this->tag->endForm(); ?>
