<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a class="navbar-brand"><img src="img/maya.jpg" /></a>
            <a class="navbar-brand">Innovación Maya</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><?php echo $this->tag->linkTo('administrador','Inicio');?></li>
                <li><?php echo $this->tag->linkTo('administrador/reporte','Reporte');?></li>
                <li><a id="terminado">Terminado</a></li>
                <!--li><?php echo $this->tag->linkTo('administrador/terminado','Terminado');?></li-->
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-user"></span> <?php echo $this->session->get("login");?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><?php echo $this->tag->linkTo('administrador/registro','Registrar Usuario');?></li>
                        <li><?php echo $this->tag->linkTo('administrador/consulta','Consulta Usuario');?></li>
                    </ul>
                </li>
                <li><?php echo $this->tag->linkTo('administrador/salir','<span class="glyphicon glyphicon-log-out"></span> Salir');?></li>
            </ul>
        </div>
    </div>
</nav>
<br>
<br>
<div class="row center-block">
    <?php echo $this->getContent(); ?>
</div>