<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span> 
            </button>
            <a class="navbar-brand"><img src="img/maya.jpg"/></a>
            <a class="navbar-brand">Innovación Maya</a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li class="active"><?php echo $this->tag->linkTo('programador','Inicio');?></li>
                <!--li><a id="terminado">Terminado</a></li-->
                <li><?php echo $this->tag->linkTo('programador/terminado','Terminado');?></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a><span class="glyphicon glyphicon-user"></span> <?php echo $this->session->get("login");?></a></li>
                <li><?php echo $this->tag->linkTo('programador/salir','<span class="glyphicon glyphicon-log-out"></span> Salir');?></li>
            </ul>
        </div>
    </div>
</nav>
<br>
<br>
<div class="row center-block">
    <?php echo $this->getContent(); ?>
</div>